### ISSUE TITLE
ideal point model

### ISSUE THREAD

**Issue by RobertMyles** [goldingn/greta#46]
Hi, very interesting package, congratulations. This is the ideal point model I tried to implement with greta:

```
library(greta)
library(congressbr)

data("senate_nominal_votes")

votes <- senate_nominal_votes %>%
  dplyr::filter(vote_date >= "2007-03-01", vote_date <= "2010-12-01") %>% 
  dplyr::select(bill_id, senator_name, senator_vote)

rollcalls <- vote_to_rollcall(votes = votes$senator_vote, bills = votes$bill_id,
                              legislators = votes$senator_name, 
                              Stan = TRUE, ideal = FALSE)


# create parameters, stating their prior distributions
beta = normal(0, 3)
alpha = normal(0, 5)
xi = normal(0, 1)
sd = flat(range = c(0, 50))

y <- alpha + beta*xi

# define the likelihood of the observed data
likelihood(rollcalls$data) = normal(y, sd)

model <- define_model(alpha, beta, xi, sd)

draws <- mcmc(model, n_samples = 1000)

library(MCMCvis)

MCMCtrace(draws)
MCMCplot(draws, xlim = c(-1, 5))
```

Which gives me this:

![](http://i.imgur.com/BHpnfNa.png)

How could I tweak this to get estimates for every x_i? (Individual senators, in this case. `sd` seems odd too but I'm primarily interested in the ideal points for now, since I'm just playing around with the package). Thanks for any help!

**Comment by goldingn** [comment]
Glad it looks useful!

I'm not so familiar with this model, but I think the problem is that you `xi` is length 1, whereas you want it to have the same length as `rollcalls$data`, right?

You can see the dimensions of `xi` like this:
```r
dim(xi)
```
```
[1] 1 1
```
or just
```r
xi
```
```
greta array (stochastic)

     [,1]
[1,]   ? 
```

If you want `xi` to be a (column) vector, you need to tell it the expected dimensions, so you can switch the prior to:
```r
N <- length(rollcalls$data)
xi = normal(0, 1, dim = N) # the same as dim = c(N, 1)
```
which looks like this:
```r
dim(xi)
```
```
[1] 1921    1
```
```r
head(xi)
```
```
greta array (operation)

     [,1]
[1,]   ? 
[2,]   ? 
[3,]   ? 
[4,]   ? 
[5,]   ? 
[6,]   ?
```

so plugging that back into you model, I get:

```r
N <- length(rollcalls$data)

# create parameters, stating their prior distributions
beta = normal(0, 3)
alpha = normal(0, 5)
xi = normal(0, 1, dim = N)
sd = flat(range = c(0, 50))

y <- alpha + beta*xi

# define the likelihood of the observed data
likelihood(rollcalls$data) = normal(y, sd)

model <- define_model(alpha, beta, xi, sd)

draws <- mcmc(model, n_samples = 1000)

library(MCMCvis)

# subset to plot only the first 10!
draws2 <- draws
draws2[[1]] <- draws2[[1]][, paste0('xi', 1:10)]

MCMCplot(draws2)
```

(this takes a little bit longer to run since there are nearly 2,000 parameters)

![image](https://cloud.githubusercontent.com/assets/4450731/25570896/b128624a-2e6c-11e7-8f24-967dab3fe0c4.png)

Is that what it should look like?

**Comment by RobertMyles** [comment]
Yes, of course! Very nice. Thanks for the help!
