### ISSUE TITLE
change print method for array?

### ISSUE THREAD

**Issue by mdscheuerell** [goldingn/greta#62]
I've been playing around with `greta` and I really like some of the features, but I was wondering if perhaps you would consider changing the print method for a `greta_array`? For example, in your examples section of the README, it states:

> To make a matrix that has random variables in the first column, but zeros everywhere else, we could do:

     # a 4x3 greta array of zeros
     x <- zeros(4, 3)

     # now with random variables in the first column
     x[, 1] = normal(0, 1, dim = 4)

Thus, my expectation is that `x` should now look like
 
     ## greta array (operation)
     ## 
     ##      [,1] [,2] [,3]
     ## [1,]   ?    0    0
     ## [2,]   ?    0    0
     ## [3,]   ?    0    0
     ## [4,]   ?    0    0

but when I inspect it, I instead get

     ## greta array (operation)
     ## 
     ##      [,1] [,2] [,3]
     ## [1,]   ?    ?    ?
     ## [2,]   ?    ?    ?
     ## [3,]   ?    ?    ?
     ## [4,]   ?    ?    ?

Perhaps the print output could be modified to aid in visual inspection of the model form?

**Comment by goldingn** [comment]
Thanks Mark. Yeah, that would be nice behaviour. Potentially a but tricky to implement as currently greta only tracks the dimensions of arrays, not what's happened to individual elements. But might be possible in this case. I'll take a look.

**Comment by mdscheuerell** [comment]
OK, thanks. It's not a big deal if you're confident in your model specification, but something to think about...

**Comment by goldingn** [comment]
So this turns out not to have been so difficult after all. If you load the dev branch with `devtools::install_github('goldingn/greta@dev')`, you should get the following:

```r
 # a 4x3 greta array of zeros
 x <- zeros(4, 3)

 # now with random variables in the first column
 x[, 1] = normal(0, 1, dim = 4)

x
```
```
greta array (operation)

     [,1] [,2] [,3]
[1,]  ?   0    0   
[2,]  ?   0    0   
[3,]  ?   0    0   
[4,]  ?   0    0   
```
---

##### sidebar

I've only implemented this for replacement. If you do an operation on only greta arrays with known values, you'll still get unknowns as a result, e.g.:

```r
ones(3, 3) * 2
```
```
greta array (operation)

     [,1] [,2] [,3]
[1,]  ?    ?    ?  
[2,]  ?    ?    ?  
[3,]  ?    ?    ? 
```

I think this is the desired behaviour, because the alternative would be to do (potentially computationally expensive) operations both in R, and then later in tensorflow when fitting the model.

For the case where a greta array of fixed values is needed, I could add a `greta_array()` function to create greta arrays from data, in the same way as the `array()` constructor function. I.e.:

```r
greta_array(2, dim = c(3, 3))
```
```
greta array (data)

     [,1] [,2] [,3]
[1,]    2    2    2
[2,]    2    2    2
[3,]    2    2    2
```
or
```r
greta_array(1:3, dim = c(3, 3))
```
```
greta array (data)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    2    2    2
[3,]    3    3    3
```

Does that sound like it would be useful @mdscheuerell?

**Comment by mdscheuerell** [comment]
Thanks, Nick!

Re: the `greta_array` function, I think it would be useful for cases where you want to specify a design matrix and fixed covariates for 1+ intervention(s) in a multivariate state-space model. Or, when you have *N* observations of *M* states, and *N* > *M*, you would want a matrix **Z** containing only 1's & 0', which maps the *i*-th observation onto the *j*-th state.

**Comment by goldingn** [comment]
Cool, thanks. It would actually just be an alias for `as_data(array(...))`, but worth including for convenience I think.

**Comment by goldingn** [comment]
the `greta_array()` constructor is now implemented on dev
